channels:
  - conda-forge
  - defaults
  - ioam
  - pyviz
dependencies:
  - iris=2.1.0=py36_2
  - jupyterlab=0.32.1=py36_0
  - ipyleaflet==0.9.0
  - nodejs==8.10.0
  - holoviews==1.10.7
  - geoviews==1.5.3
  - xarray==0.10.8
  - notebook==5.6.0
  - datashader==0.6.6
  - pip:
    - jupyterlab_thredds==0.1.0
    - jupyterlab-discovery==5.1.2
    - nc_time_axis==1.1.0
