channels:
  - conda-forge
  - defaults
  - ioam
  - pyviz
dependencies:
  - iris=2.2.0=py36_2
  - cf_units==2.0.1
  - jupyterlab=0.35.4=py36_0
  - ipyleaflet==0.9.0
  - nodejs==8.10.0
  - holoviews==1.10.9
  - geoviews==1.5.3
  - xarray==0.10.9
  - notebook==5.7.2
  - datashader==0.6.8
  - pip:
    - jupyterlab_thredds==0.3.0
    - nc_time_axis==1.1.0
    - tqdm
