channels:
  - conda-forge
  - defaults
  - ioam
dependencies:
  - iris=2.0.0=py36_1
  - jupyterlab=0.32.1=py36_0
  - ipyleaflet==0.8.1
  - nodejs==8.10.0
  - holoviews==1.10.4
  - geoviews==1.5.0
  - xarray==0.10.4
  - nc_time_axis==1.0.2
  - notebook==5.5.0
  - datashader==0.6.5
  - pip:
    - jupyterlab_thredds==0.1.0
    - jupyterlab-discovery==5.1.2
